version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    container_name: backend_service
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/ordersdb
      - PORT=3000
      - FRONTEND_URL=http://localhost:8080
    networks:
      - app-network
    volumes:
      - ./packages/backend/src:/app/src 

  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile
    container_name: frontend_service
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - VITE_API_BASE_URL=http://localhost:3000/api
    volumes:
      - ./packages/frontend/src:/app/src

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
